vault_user_admin_password_hash: ENC[AES256_GCM,data:r8qaAErgbCAqW8L+mO25+WTIUjWuzvx0fH5VvXfM7qF/b39fHfbWNFGKra5wDPjMs0RFTJVKlMkJ/kSadaqhAzBkOFdqsUkXOA==,iv:O4zrIVjPPijXVkHeO6AlfNbzgt3keawZGSHHkBl1Ix8=,tag:wAEopEbgR7V62Hj70uz9ig==,type:str]
vault_ansible_ssh_private_key: ENC[AES256_GCM,data:4x/dvAgehK9XjkKkP9F9tqmh754lYRBW1M2A5h0xWZmT26WGMzCfveOd2nSOvM5M1IdsNczIyUCVhTgoYGS8e0S3vCoi6dDcH3Nwrw+AMkL8xtOhKGDA+HpqVF2MJOIWA+xZNhlQy85PtWNPKZVWWZMQ57opWDpheOxVFRAt6EpWCECNHFYm6jhg4ogE4knx3BHsigx9FdMoSk3xt7IJNbkkzPsNhl2kRM4F3DcO5MDcrikoDHlvB7gVsuog1O3p16pK6VqP1dGkT9nISOaQm03WUHrxmCYsjMK5Dgjq7+SVIbdJLTQgWkrNYS4a2fJZcQmkkcsVFovnOfJKnLOY7CYQRQPU20tGmgW5d+oCvqZWLF5IKYxrWdz0TKq24TwJFthAEW+4NKVEHnVrHUuiCOUs/pfFOkXACfLz9lvwDqpw45WP/20yeAYYDxbO6BX8159uCtrsazmZBromOn4b6WyaOH+wSB7+M5diBY46fdSsSQNs9Oxh5zMwMrySXD6oAMf/2usrpriAINnAb3k6xESYX+um87voZmE3,iv:kaYRkU3sRTBxlQkQVDgXe8DKnxiWSbw6VYfmI6SPcik=,tag:hsDbCFUPxe6wJVsrL0iOfg==,type:str]
vault_authentik_pg_pass: ENC[AES256_GCM,data:ggatkerU/7LMjB9jG4FWKP1x6NU6lzyzEJ6ULawUrHcx0mR8m0lrMhiVyxXvNQqu,iv:vVg0WB3T6yp1cvg7/MxPCD5Re3fQRagqGtXN0jUxO4s=,tag:g6EeS8b1TmFXdXpW6plr3Q==,type:str]
vault_authentik_secret_key: ENC[AES256_GCM,data:ugmqWeQCda7/LNBMd985SpF0xc/kAXSlFKRbNuhsyhX9sts/ZKZMTIt1/GJeEw/7gFTsxA4+RNd3RcMaoHJPZ0xntQ9dIjiSjyhY2G9rx5c=,iv:L9wdb9VOFvAzVTxMPs2IlaOP8lb19eiayYZgA+Z7jwU=,tag:VbTVHyszhsoPYFEmyyHjgg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OEdUa2huRGVPQjBieDRL
        cGNFZkdsV0tvbEhqanRmRi9jQWV1K3RYQWhFCjhtKzRZOEJIUS9ONjRHOGRxZ2Jk
        WGZvR0k0Wk9YT3hwUmw0OTJwbGtnTVUKLS0tIGo3MkowYjZzOTRmV3lLMVk1YTBF
        Mmx0WjFuUDFxUmpwcm5vNGtSbXYvQXMKPGaydfgnowKy+SZvKmRoNXkiriABPCkK
        jGwouM0uIE6EYs2EQSmXi2weZOz6lIOWACez73pGrO/6mWoynxujOg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fy6uscr0f263jdksk0djy3fu7996zhm8mvnajnpay4fr3d2x7dyqgar94x
  lastmodified: "2026-07-28T06:47:02Z"
  mac: ENC[AES256_GCM,data:35LH285jgwVi+c88R3IZjZMi7IH5na3D5F7LzL5CPDM/p10JKBP5qv6oG2JotUZTLlxe41M8xK2rYFd5ceqU7WUQGfSJmBm3M/CusL3Hsqw4fzHfu/GFqmfe74MQpbOKwnjyJFBN5oGTPP5AM9hOJ3lkaEvyxWOEErjZ6I830ig=,iv:4C0qnBO7Io9OA6HWWrlBs+eDhjcMPfXerNX4Fm0gAh4=,tag:SH3gfRjnrnpuSNaVcKTXkQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.2
