user_admin_password_hash: ENC[AES256_GCM,data:4dHyiZV7pPyXBWaxGICuYpRzOKtjaQsUaxH0xrk5L+4j5cTwhYPCjIEZwabs7ecKKd1sgy1UtAvPNNliHLIPtMjDxDJhOjjUng==,iv:6GwrzZQJEG+CiT572JfRm53HzJcu7QWJhkV9Ko1RqHY=,tag:dwLiJ6jizEMLoKsvHwJSKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OEdUa2huRGVPQjBieDRL
            cGNFZkdsV0tvbEhqanRmRi9jQWV1K3RYQWhFCjhtKzRZOEJIUS9ONjRHOGRxZ2Jk
            WGZvR0k0Wk9YT3hwUmw0OTJwbGtnTVUKLS0tIGo3MkowYjZzOTRmV3lLMVk1YTBF
            Mmx0WjFuUDFxUmpwcm5vNGtSbXYvQXMKPGaydfgnowKy+SZvKmRoNXkiriABPCkK
            jGwouM0uIE6EYs2EQSmXi2weZOz6lIOWACez73pGrO/6mWoynxujOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fy6uscr0f263jdksk0djy3fu7996zhm8mvnajnpay4fr3d2x7dyqgar94x
    lastmodified: "2026-07-23T07:11:28Z"
    mac: ENC[AES256_GCM,data:+uwMp72G9nNnJY9vK3+uPtZ8nWfn+o7ltwmzMqZxtrrFZS1a2eC3FvJn+yySRxNAzwqmewAJPw1f/uZ7t9IGEp6MImlvp8jBStc5/LEA5W0c4EIZltK3rVIxZ35+VN1Mrc1pIGSOivTUeOGhWuVldLRG0ofVK1nFDPlFMDJp4yo=,iv:CrYCJeIkiZVGlwDC3QHte0r52X/Mcs++sgWoSourArM=,tag:6v5iloW3aDWoG5Ekl9EmLw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
