- name: Ensure the ansible service account is present and can sudo
  ansible.builtin.import_tasks: service_account.yml

- name: Set the system timezone
  community.general.timezone:
    name: "{{ base_common_timezone }}"

- name: Install baseline packages
  ansible.builtin.apt:
    name: "{{ base_common_packages }}"
    cache_valid_time: "{{ base_common_cache_valid_time }}"
    state: present
    update_cache: true

#- name: Install pipx packages
#  community.general.pipx:
#    name: "{{ item }}"
#  loop: "{{ base_common_pipx_packages }}"

- name: Clear stale package cache
  ansible.builtin.apt:
    autoclean: true
  tags: [maintenance]

- name: Create user admin account
  ansible.builtin.user:
    name: "{{ user_admin_account_name }}"
    password: "{{ user_admin_password_hash }}"
    shell: "/usr/bin/zsh"
  no_log: true

- name: Increase user admin sudo timeout to 90 minutes
  ansible.builtin.copy:
    dest: /etc/sudoers.d/madmin
    content: "Defaults: madmin timestamp_timeout=90\n"
    mode: "0440"
    validate: visudo -cf %s

- name: Add SSH key to authorized users
  ansible.posix.authorized_key:
    user: "{{ user_admin_account_name }}"
    state: present
    key: "{{ lookup('file', user_admin_ssh_key_public_key_path) }}"

- name: Apply sshd config for hardening
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
    mode: "0644"
  notify: Reload sshd

- name: Copy .zshrc to user account home
  ansible.builtin.copy:
    src: .zshrc
    dest: "/home/{{ user_admin_account_name }}/.zshrc"
    owner: "{{ user_admin_account_name }}"
    group: "{{ user_admin_account_name }}"
    mode: "0644"

- name: Sync zsh plugins
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/zsh-plugins/"
    dest: "/home/{{ user_admin_account_name }}/.zsh/"
    delete: true
    recursive: true
    rsync_path: "sudo rsync"

- name: Fix ownership of synced plugins
  ansible.builtin.file:
    path: "/home/{{ user_admin_account_name }}/.zsh/"
    state: directory
    owner: "{{ user_admin_account_name }}"
    group: "{{ user_admin_account_name }}"
    recurse: true

- name: Drop .tmux.conf for users
  ansible.builtin.copy:
    src: .tmux.conf
    dest: "/home/{{ user_admin_account_name }}/.tmux.conf"
    owner: "{{ user_admin_account_name }}"
    group: "{{ user_admin_account_name }}"
    mode: "0644"

- name: Create directory for journald
  ansible.builtin.file:
    path: "/etc/systemd/journald.conf.d"
    state: directory
    mode: "0755"

- name: Configure journald persistence and retention
  ansible.builtin.template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf.d/99-homelab.conf
    mode: "0644"
  notify: Restart journald
