- name: Create ansible group
  ansible.builtin.group:
    name: ansible
    state: present

- name: Create ansible user
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    group: ansible
    password_lock: true
    state: present
    shell: /bin/bash

- name: Add SSH key to authorized users
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', service_ssh_public_key_path) }}"

- name: Add ansible group to passwordless sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ansible
    content: "%ansible ALL=(ALL) NOPASSWD:ALL\n"
    mode: "0440"
    validate: "visudo -cf %s"
