- name: Baseline config
  hosts: all
  become: true
  roles:
    - role: base_common
      tags: [base, common]

- name: Kernel tuning
  hosts: vm,proxmox
  become: true
  roles:
    - role: kernel_tuning
      tags: [base, kernel]

