all:
  children:
    proxmox:
      hosts:
        mini-pc-pve: { ansible_host: 10.0.0.21 }
        nas-pve: { ansible_host: 10.0.0.32 }
    guests:
      children:
        lxc:
          hosts:
            adguard01: { ansible_host: 10.0.0.25 }
            caddy01: { ansible_host: 10.0.0.5 }
            authentik01: { ansible_host: 10.0.0.3 }
            arr02: { ansible_host: 10.0.0.35 }
            jellyfin01: { ansible_host: 10.0.0.34 }
        vm:
          hosts:
            docker-arr01: { ansible_host: 10.0.0.8 }
        workstation:
          hosts:
            c-dev01: { ansible_host: 10.0.0.28 }
            work-shell01: { ansible_connection: local }
    control:
      hosts:
        work-shell01:
